### PR TITLE
Prevent Formater from changing a 0 ind to ' '

### PR DESCRIPTION
**Pull request by nlegrand**
I'm not sure this is the write way to do it, anyway, there is something to do to preserve the '0' indicator which is legit :).

### CODE REVIEW

**Comment by fredericd** [comment]
And why not replacing directly (if possible):

`$field->ind1 || ' '`
with:

`defined($field->ind1) ? $field->ind1 : ' '`

**Comment by nlegrand** [comment]
It's working this way ! I've amended and force-pushed the commit.

**Comment by fredericd** [comment]
Thanks Nicolas. It's also released on CPAN.

**Comment by nlegrand** [comment]
Great! Thank you!

**Pull request merged**
